# Generated by Django 4.1.7 on 2023-03-05 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persosonal_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('dob', models.DateField(null=True)),
                ('gender', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'persosonal_info',
            },
        ),
        migrations.CreateModel(
            name='Work_Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.persosonal_info')),
            ],
            options={
                'db_table': 'work_experience',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills_name', models.CharField(max_length=50)),
                ('skills_level', models.CharField(max_length=50)),
                ('skills_category', models.CharField(max_length=50)),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.persosonal_info')),
            ],
            options={
                'db_table': 'skills',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('education_level', models.CharField(max_length=50, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('personal_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.persosonal_info')),
            ],
            options={
                'db_table': 'education',
            },
        ),
    ]
