# Generated by Django 4.1.7 on 2023-03-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persosonal_info',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='persosonal_info',
            name='password',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
