# Generated by Django 4.1.7 on 2023-03-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_persosonal_info_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persosonal_info',
            name='image',
            field=models.ImageField(default=2, upload_to='images/'),
            preserve_default=False,
        ),
    ]
