# Generated by Django 4.1.7 on 2023-03-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_persosonal_info_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
            options={
                'db_table': 'images',
            },
        ),
        migrations.RemoveField(
            model_name='persosonal_info',
            name='image',
        ),
    ]
