# Generated by Django 4.1.7 on 2023-04-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_talent_talentcategories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='website',
            field=models.CharField(max_length=255),
        ),
    ]
