# Generated by Django 4.1.7 on 2023-03-06 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_personal_img_remove_persosonal_info_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_img',
            name='personal_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.persosonal_info'),
            preserve_default=False,
        ),
    ]
