# Generated by Django 4.1.7 on 2023-04-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_employer_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='closing_date',
            field=models.DateField(null=True),
        ),
    ]
