# Generated by Django 4.1.7 on 2023-04-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_talent_closing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='duties_and_respo',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='talent',
            name='qualification',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
