# Generated by Django 4.1.7 on 2023-03-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_personal_img_personal_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_img',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
