# Generated by Django 4.1.7 on 2023-03-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_personal_img_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='persosonal_info',
            name='image',
            field=models.ImageField(default=0, upload_to='images/'),
            preserve_default=False,
        ),
    ]
