# Generated by Django 4.1.7 on 2023-03-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_persosonal_info_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persosonal_info',
            name='user_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
