# Generated by Django 4.1.7 on 2023-03-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_persosonal_info_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persosonal_info',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
