# Generated by Django 4.1.7 on 2023-03-06 09:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_persosonal_info_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal_img',
            name='name',
        ),
        migrations.RemoveField(
            model_name='persosonal_info',
            name='image',
        ),
        migrations.AlterField(
            model_name='personal_img',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
