# Generated by Django 4.1.7 on 2023-03-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_personal_img_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_img',
            name='bio',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
