# Generated by Django 4.1.7 on 2023-03-10 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0017_alter_education_user_alter_personal_img_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='skills_category',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='skills_level',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='user',
        ),
        migrations.CreateModel(
            name='Personal_Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.skills')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Personal_Skills',
            },
        ),
    ]
