# Generated by Django 4.1.7 on 2023-03-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_rename_skills_personal_skills_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='skills_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
